version: '3.8'

services:
  app:
    build: .
    container_name: comparei-servico-usuario
    ports:
      - "8080:8080"
    depends_on:
      - mongo-user
      - redis
    networks:
      - net_user
      - comparei_net
    command: ["./wait-for-it.sh", "mongo-user:27017", "--", "./main"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
  mongo-user:
    image: mongo:latest
    container_name: mongo-user
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: userdb
      MONGO_INITDB_DATABASE: userdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - net_user
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "768M"
  redis:
    image: redis:7
    container_name: redis_user
    networks:
      - net_user
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"

networks:
  net_user:
    driver: bridge
  
  comparei_net:
    external: true

volumes:
  mongo_data: