version: '3.8'

services:
  app:
    build: .
    container_name: comparei-servico-usuario
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - net_user
    command: ["./wait-for-it.sh", "db", "--", "./main"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
  db:
    image: mysql:8
    container_name: mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net_user
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "768M"
  redis:
    image: redis:7
    container_name: redis_user
    networks:
      - net_user
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"

networks:
  net_user:
    driver: bridge
