@token = {{ login.response.body.token }}

###
# @name user

post {{host}}/user
Content-Type: application/json
apiKey: {{apiKey}}

{
    "name": "Vinícius Teste",
    "username": "vini",
    "email": "vini@teste.com",
    "password": "12345678"
}

###
get {{host}}/users
Content-Type: application/json
apiKey: {{apiKey}}

###
get {{host}}/user/680e92d8820039eb6f362a47
Content-Type: application/json
apiKey: {{apiKey}}

###
# @name updateUser

put {{host}}/user/5
Content-Type: application/json
apiKey: {{apiKey}}

{
    "name": "Updated Name",
    "username": "updated_username_up",
    "email": "updated_email5@teste.com",
    "status": 1,
    "photo": "",
    "ray_distance": 15,
    "level": 1
}

###
# @name deleteUser

delete {{host}}/user/3
Content-Type: application/json
apiKey: {{apiKey}}

###
# @name login

post {{host}}/login
Content-Type: application/json
apiKey: {{apiKey}}

{
    "username": "vini",
    "password": "12345678"
}

###
# @name validateToken

get {{host}}/validate-token
Content-Type: application/json
apiKey: {{apiKey}}
Authorization: Bearer {{token}}

###
# @name clearRedis

post {{host}}/clear-redis
Content-Type: application/json
apiKey: {{apiKey}}
